### ISSUE TITLE
sprawdziłem zadania

### ISSUE THREAD

**Issue by k-basinski** [ArletaBanasik/tipn_zadArletaBanasik#2]
- Zad5-1 jest źle - nie ma importu, a komenda `library(movies)` jest bez sensu. Nie będę sprawdzał reszty zadania 5 jeśli nie ma importu.
- Zad6 ok.

**Comment by ArletaBanasik** [comment]
Poprawiłam zadanie 5. 
Teraz chyba jest już ok

**Comment by k-basinski** [comment]
Dobra, teraz jest ok. Przedmiot zaliczony!
